# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KingsCup' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KingsCup

  

  platform :ios, '9.0'
  target 'KingsCupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KingsCup-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KingsCup-tvOS

  target 'KingsCup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
